AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Send Cost Repport to elastcisearch with AWS Lambda function
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  costExplorer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: costExplorer Lambda function.
      MemorySize: 512
      Timeout: 3
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter